# ???????
spring.application.name=magic_conch_backend
server.port=8080

# ?????
ai.service.host=localhost
ai.service.port=80

# ?????
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# MyBatis-Plus ??
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# ??????????? .env
spring.config.import=optional:file:./.env[.properties]